spring.application.name=ims

spring.application.name=ims

spring.datasource.url=${DB_URL:jdbc:postgresql://caboose.proxy.rlwy.net:21625/railway?sslmode=require}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:TLRClTSNdBmblyDsgUPxKmmHTcZSTBJS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}

app.jwt.secret=ims_super_secret_key_change_this_in_production_2024
app.jwt.expiration=86400000

spring.web.cors.allowed-origins=http://localhost:3000,https://ims-frontend-navy.vercel.app/

# Server Port (Render compatible)
server.port=${PORT:8080}

# JWT Secret & Expiry
app.jwt.secret=ims_super_secret_key_change_this_in_production_2024
app.jwt.expiration=86400000

# CORS
spring.web.cors.allowed-origins=http://localhost:3000!